### ISSUE TITLE
Getting instance properties/values

### ISSUE THREAD

**Issue by kagd** [autoric/scheming#22]
Is there a way to get the properties and values of an instance as an object without explicitly calling each property? 

I can get them by doing something like this:

```js
newUser = new User({email: 'foo@bar.com'})
userObject = User.getProperties()
params = {}
_.each userObject, (value, key) ->
  params[key] = newUser[key]
```

But I would love it if there was a method on the instance to do that. Does that exist and I just missed it?

**Comment by autoric** [comment]
There is no method on the instance to do that. The only method on the instance prototype is `.watch`, which is intentional. In general the goal is for instances to be pure representations of state, with as little attached functionality or risk of key conflicts as possible.

Having said that, I'm not sure I understand the problem you are trying to solve. You are trying to get a pojo from a scheming instance?  The code sample you have above could be simplified to:

```javascript
newUser = new User({email: 'foo@bar.com'})
params = _.clone(newUser)
```

**Comment by kagd** [comment]
Awesome! That is exactly what I was trying to get but didn't know how. Thanks.

**Comment by autoric** [comment]
No problem. 

Note that `_.clone` does a shallow copy, so object references will be preserved. For nested schemas you will probably want to use `_.cloneDeep` to walk the entire object tree and convert to a pojo.

This can be expensive for large or deeply nested objects, so you don't necessarily want do it a lot.
